# Generated by Django 2.2.5 on 2019-09-11 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'verbose_name': 'registro', 'verbose_name_plural': 'registros'},
        ),
        migrations.AddField(
            model_name='transfer',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
            preserve_default=False,
        ),
    ]
