# Generated by Django 2.2.6 on 2019-10-14 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191008_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='category',
        ),
        migrations.RemoveField(
            model_name='record',
            name='observation',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
